config/routes.rb
Rails.application.routes.draw do
  resources :moviments
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :categories
  resources :unities
  resources :products
  resources :stores
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  post 'importar' => 'moviments#importar', as: :importar

  namespace :api do

    get 'products' => 'products#index', as: :products_index
    get 'products/:id' => 'products#show', as: :products_show

    get 'stores' => 'stores#index', as: :stores_index
    get 'stores/:id' => 'stores#show', as: :stores_show

    get 'categories' => 'categories#index', as: :categories_index

    post 'products/buy' => 'products#buy', as: :buy

    post 'mailer/send_mail' => 'mailer#send_mail', as: :send_mail

  end


end

app/models/store.rb
class Store < ApplicationRecord
  has_many :products
  # audited max_audits: 100
end

app/controllers/api/stores_controller.rb
module Api
  class StoresController < ApiController

    def index
      render json: Store.all
    end

    def show
      render json: Store.find(params[:id])
    end

  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: I18n.t('sucesso') }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: I18n.t('sucesso') }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy

    msg = 'deleted'

    unless Moviment.find_by_store_id(@store.id)
      @store.destroy
    else
      msg = 'cant_destroy_store'
    end

    respond_to do |format|
      format.html { redirect_to stores_url, notice: I18n.t(msg) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :address, :phone, :description)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t('name') %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label t('address') %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label t('phone') %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label t('description') %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit t('Save') %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1><%=  "#{t('editing')} #{t('Store')}"  %></h1>

<%= render 'form', store: @store %>

<%= link_to t('Show'), @store, class: "black-text waves-effect waves-light btn blue" %>
<%= link_to t('Back'), stores_path, class: "black-text waves-effect waves-light btn blue" %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('Stores') %></h1>

<table>
  <thead>
  <tr>
    <th><%= t('name') %></th>
    <th><%= t('address') %></th>
    <th><%= t('phone') %></th>
    <th><%= t('description') %></th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @stores.each do |store| %>
    <tr>
      <td><%= store.name %></td>
      <td><%= store.address %></td>
      <td><%= store.phone %></td>
      <td><%= store.description %></td>
      <td><%= link_to t('Show'), store %></td>
      <td><%= link_to t('Edit'), edit_store_path(store) %></td>
      <td><%= link_to t('Destroy'), store, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to t('novo'), new_store_path, class: "waves-effect waves-light btn blue black-text" %>

app/views/stores/new.html.erb
<h1><%=  "#{t('nova')} #{t('Store')}"  %></h1>

<%= render 'form', store: @store %>

<%= link_to t('Back'), stores_path, class: "black-text waves-effect waves-light btn blue" %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('name') %>:</strong>
  <%= @store.name %>
</p>

<p>
  <strong><%= t('address') %>:</strong>
  <%= @store.address %>
</p>

<p>
  <strong><%= t('phone') %>:</strong>
  <%= @store.phone %>
</p>

<p>
  <strong><%= t('description') %>:</strong>
  <%= @store.description %>
</p>

<%= link_to t('Edit'), edit_store_path(@store), class: "black-text waves-effect waves-light btn blue" %>
<%= link_to t('Back'), stores_path, class: "black-text waves-effect waves-light btn blue" %>