config/routes.rb
Rails.application.routes.draw do
  resources :moviments
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :categories
  resources :unities
  resources :products
  resources :stores
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  post 'importar' => 'moviments#importar', as: :importar

  namespace :api do

    get 'products' => 'products#index', as: :products_index
    get 'products/:id' => 'products#show', as: :products_show

    get 'stores' => 'stores#index', as: :stores_index
    get 'stores/:id' => 'stores#show', as: :stores_show

    get 'categories' => 'categories#index', as: :categories_index

    post 'products/buy' => 'products#buy', as: :buy

    post 'mailer/send_mail' => 'mailer#send_mail', as: :send_mail

  end


end

app/models/unity.rb
class Unity < ApplicationRecord
end

app/controllers/unities_controller.rb
class UnitiesController < ApplicationController
  before_action :set_unity, only: [:show, :edit, :update, :destroy]

  # GET /unities
  # GET /unities.json
  def index
    @unities = Unity.all
  end

  # GET /unities/1
  # GET /unities/1.json
  def show
  end

  # GET /unities/new
  def new
    @unity = Unity.new
  end

  # GET /unities/1/edit
  def edit
  end

  # POST /unities
  # POST /unities.json
  def create
    @unity = Unity.new(unity_params)

    respond_to do |format|
      if @unity.save
        format.html { redirect_to @unity, notice: I18n.t('sucesso') }
        format.json { render :show, status: :created, location: @unity }
      else
        format.html { render :new }
        format.json { render json: @unity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unities/1
  # PATCH/PUT /unities/1.json
  def update
    respond_to do |format|
      if @unity.update(unity_params)
        format.html { redirect_to @unity, notice: I18n.t('sucesso') }
        format.json { render :show, status: :ok, location: @unity }
      else
        format.html { render :edit }
        format.json { render json: @unity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unities/1
  # DELETE /unities/1.json
  def destroy
    @unity.destroy
    respond_to do |format|
      format.html { redirect_to unities_url, notice: I18n.t('deleted') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unity
      @unity = Unity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unity_params
      params.require(:unity).permit(:name)
    end
end

app/helpers/unities_helper.rb
module UnitiesHelper
end

app/views/unities/_form.html.erb
<%= form_with(model: unity, local: true) do |form| %>
  <% if unity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unity.errors.count, "error") %> prohibited this unity from being saved:</h2>

      <ul>
        <% unity.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t('name') %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit t('Save') %>
  </div>
<% end %>

app/views/unities/edit.html.erb
<h1><%=  "#{t('editing')} #{t('Unity')}"  %></h1>

<%= render 'form', unity: @unity %>

<%= link_to t('Show'), @unity, class: "black-text waves-effect waves-light btn blue" %>
<%= link_to t('Back'), unities_path, class: "black-text waves-effect waves-light btn blue" %>

app/views/unities/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('Unities') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('name') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unities.each do |unity| %>
      <tr>
        <td><%= unity.name %></td>
        <td><%= link_to t('Show'), unity %></td>
        <td><%= link_to t('Edit'), edit_unity_path(unity) %></td>
        <td><%= link_to t('Destroy'), unity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('novo'), new_unity_path, class: "waves-effect waves-light btn blue black-text" %>

app/views/unities/new.html.erb
<h1><%=  "#{t('nova')} #{t('Unity')}"  %></h1>

<%= render 'form', unity: @unity %>

<%= link_to t('Back'), unities_path, class: "black-text waves-effect waves-light btn blue" %>

app/views/unities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @unity.name %>
</p>

<%= link_to t('Edit'), edit_unity_path(@unity), class: "black-text waves-effect waves-light btn blue" %>
<%= link_to t('Back'), unities_path, class: "black-text waves-effect waves-light btn blue" %>