config/routes.rb
Rails.application.routes.draw do
  resources :moviments
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :categories
  resources :unities
  resources :products
  resources :stores
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  post 'importar' => 'moviments#importar', as: :importar

  namespace :api do

    get 'products' => 'products#index', as: :products_index
    get 'products/:id' => 'products#show', as: :products_show

    get 'stores' => 'stores#index', as: :stores_index
    get 'stores/:id' => 'stores#show', as: :stores_show

    get 'categories' => 'categories#index', as: :categories_index

    post 'products/buy' => 'products#buy', as: :buy

    post 'mailer/send_mail' => 'mailer#send_mail', as: :send_mail

  end


end

app/models/category.rb
class Category < ApplicationRecord
end

app/controllers/api/categories_controller.rb
module Api
    class CategoriesController < ApiController
        def index
            render json: Category.all
        end    
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: I18n.t('sucesso') }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: I18n.t('sucesso') }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy

    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: t("deleted") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t('name') %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit t("Save") %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%=  "#{t('editing')} #{t('category')}"  %></h1>

<%= render 'form', category: @category %>

<%= link_to t('Show'), @category, class: "black-text waves-effect waves-light btn blue" %>
<%= link_to t('Back'), categories_path, class: "black-text waves-effect waves-light btn blue" %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('Categories') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('name') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to t('Show'), category %></td>
        <td><%= link_to t('Edit'), edit_category_path(category) %></td>
        <td><%= link_to t('Destroy'), category, method: :delete, data: { confirm: t('Are you sure?') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "#{t('nova')} #{t('Category')}", new_category_path, :class => "waves-effect waves-light btn blue black-text" %>

app/views/categories/new.html.erb
<h1><%=  "#{t('nova')} #{t('category')}"  %></h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path, class: "black-text waves-effect waves-light btn blue" %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('name') %>:</strong>
  <%= @category.name %>
</p>

<%= link_to t('Edit'), edit_category_path(@category), class: "black-text waves-effect waves-light btn blue" %>
<%= link_to t('Back'), categories_path, class: "black-text waves-effect waves-light btn blue" %>