config/routes.rb
Rails.application.routes.draw do
  resources :moviments
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :categories
  resources :unities
  resources :products
  resources :stores
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  post 'importar' => 'moviments#importar', as: :importar

  namespace :api do

    get 'products' => 'products#index', as: :products_index
    get 'products/:id' => 'products#show', as: :products_show

    get 'stores' => 'stores#index', as: :stores_index
    get 'stores/:id' => 'stores#show', as: :stores_show

    get 'categories' => 'categories#index', as: :categories_index

    post 'products/buy' => 'products#buy', as: :buy

    post 'mailer/send_mail' => 'mailer#send_mail', as: :send_mail

  end


end

app/models/product.rb
class Product < ApplicationRecord
  #audited max_audits: 100

  mount_uploader :avatar, AvatarUploader

  validate :validate_price, on: [:update, :save]
  validates :price_cost, presence: true
  validates :price_sell, presence: true
  validates :name, presence: true
  validates :category, presence: true


  def validate_price
    errors.add(:price_sell, I18n.t('deve ser maior que price_cost')) if self.price_cost >= self.price_sell
  end

end

app/controllers/api/products_controller.rb
module Api
  class ProductsController < ApiController
    #protect_from_forgery with: :null_session

    def index
      result = []

      produtos = Product.all
      produtos = Product.where(category: params[:category]) unless (params[:category].blank?)

      produtos.each do |product|

        avatar = Base64.encode64(File.read(product.avatar.path)) rescue ""

        result << {
            "id" => "#{product.id}",
            "name" => "#{product.name}",
            "description" => "#{product.description}",
            "price_sell" => "#{product.price_sell}",
            "unity" => "#{product.unity}",
            "category" => "#{product.category}",
            "avatar" => avatar
        }.to_h

      end

      render json: result
    end

    def show

      result = Product.find_by(id: params[:id])

      # result = {
      #     "id" => "#{result.id}",
      #     "name" => "#{result.name}",
      #     "description" => "#{result.description}",
      #     "price_sell" => "#{result.price_sell}",
      #     "unity" => "#{result.unity}",
      #     "avatar" => "#{Base64.encode64(File.read(result.avatar.path)) unless result.avatar.file.nil?}"
      # }

      unless result.nil?
        render json: result 
      else
        render json: { status: 404, messages: "Product Not Found - #{params[:id]}" }, status: 404
      end

    end

    def buy

      ids = []

      ActiveRecord::Base.transaction do
        params[:buy].each do |buy|
          product = Product.find(buy[:id])

          unless product.nil?
            moviment = Moviment.create!(
                product_id: product.id,
                store_id: buy[:store_id],
                quantity: buy[:quantity],
                price_sell: product.price_sell,
                price_cost: product.price_cost,
                origin: 'api'
            )

            ids << moviment.id

          end
        end
      end

      render json: ids

    end

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: I18n.t('sucesso') }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: I18n.t('sucesso') }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy

    msg = 'deleted'

    unless Moviment.find_by_product_id(@product.id)
      @product.destroy
    else
      msg = 'cant_destroy_store'
    end

    respond_to do |format|
      format.html { redirect_to products_url, notice: I18n.t(msg) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price_cost, :price_sell, :unity, :category, :avatar)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t('image') %>
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= f.label t('name') %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label t('description') %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label t('price_cost') %>
    <%= f.text_field :price_cost %>
  </div>

  <div class="field">
    <%= f.label t('price_sell') %>
    <%= f.text_field :price_sell %>
  </div>

  <div class="field">
    <%= f.label t('category') %>
    <select name="product[category]" id="unity" class="browser-default">
      <option value="" disabled selected>Category</option>
      <% Category.all.each do |category| %>
        <option <%= "#{ "selected" if product&.category&.include?(category.name) }" %> value="<%= category.name %>"><%= category.name %> </option>
      <% end %>
    </select>
  </div>

  <div class="field">
    <%= f.label t('Unity') %>
    <select name="product[unity]" id="unity" class="browser-default">
      <option value="" disabled selected>Unity</option>
      <% Unity.all.each do |unity| %>
        <option <%= "#{ "selected" if product&.unity&.include?(unity.name) }" %> value="<%= unity.name %>"><%= unity.name %> </option>
      <% end %>
    </select>
  </div>

  <div class="actions">
    <%= f.submit t("Save") %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1><%=  "#{t('editing')} #{t('Product')}"  %></h1>

<%= render 'form', product: @product %>

<%= link_to t('Show'), @product, class: "black-text waves-effect waves-light btn blue" %>
<%= link_to t('Back'), products_path, class: "black-text waves-effect waves-light btn blue" %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('products') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('name') %></th>
      <th><%= t('description') %></th>
      <th><%= t('price_cost') %></th>
      <th><%= t('price_sell') %></th>
      <th><%= t('category') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price_cost %></td>
        <td><%= product.price_sell %></td>
        <td><%= product.category %></td>
        <td><%= link_to t('Show'), product %></td>
        <td><%= link_to t('Edit'), edit_product_path(product) %></td>
        <td><%= link_to t('Destroy'), product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('novo'), new_product_path, class: "waves-effect waves-light btn blue black-text" %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to t('Back'), products_path, class: "black-text waves-effect waves-light btn blue" %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag(@product.avatar_url) if @product.avatar? %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Unity:</strong>
  <%= @product.unity %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Price Sell:</strong>
  <%= @product.price_sell %>
</p>

<p>
  <strong>Price Cost:</strong>
  <%= @product.price_cost %>
</p>

<%= link_to t('Edit'), edit_product_path(@product), class: "black-text waves-effect waves-light btn blue" %>
<%= link_to t('Back'), products_path, class: "black-text waves-effect waves-light btn blue" %>